### ISSUE TITLE
新加的文件需要重新运行npm run dev才能生效吗？

### ISSUE THREAD

**Issue by QzhouZ** [cnu4/Webpack-Vue-MultiplePage#1]
很感谢哥们整理的说明，让我收获不少，这里有个问题请教一下。
### 场景描述

运行`npm run dev`进行开发，这时候我加了一个新的页面，`webpack-dev-server`好像并不识别，需要重新运行`npm run dev`才能识别，只能这样吗？
这种多入口模式，我每加一个业务js文件(作为新的入口)或html文件，都需要重新运行一遍才有效，感觉有点麻烦。

**Comment by cnu4** [comment]
貌似只能这样了，新加一个html文件后需要重新运行webpack，webpack的配置文件才能扫描到这个html文件并用HtmlWebpackPlugin插件生成需要的html。

**Comment by QzhouZ** [comment]
嗯，原来是这样
