### ISSUE TITLE
运行 npm run dev 后，什么都没有

### ISSUE THREAD

**Issue by cocody** [cnu4/Webpack-Vue-MultiplePage#2]
我想问问 运行 npm run dev 后，webpack-dev-server会把编译的东西放在内存中，而不是生成文件，那么对于多入口而言，输出localhost:8080，出来的到底是什么？反正我是什么都出不来

**Comment by cocody** [comment]
怎样才能访问这个在内存中的文件？

**Comment by cnu4** [comment]
需要清楚对资源文件的引用路径的配置和HTML文件的输出路径的配置

对于资源文件的输出，对应webpack配置文件中

```
output: {
    path: path.resolve(__dirname, 'Public'), // html,css,js,图片等资源文件的输出路径，将所有资源文件放在Public目录
    publicPath: '/Public/',                  // html,css,js,图片等资源文件的server上的路径
    filename: 'js/[name].[hash].js',         // 每个入口js文件的生成配置
    chunkFilename: 'js/[id].[hash].js'
  },
```

`path`是`publicPath`就是配置资源文件的输出路径，`publicPath`是资源文件的server上的引用路径

所以对于HTML文件的输出，我在webpack的配置文件中对`HtmlWebpackPlugin`插件的配置中

```
var conf = {
    filename: prod? '../Application/Home/View/' + pathname + '.html' : pathname + '.html',
    template: pages[pathname], // 模板路径
    inject: true,              // js插入位置
    minify: {
      removeComments: true,
      collapseWhitespace: false
    }
};
```

其中`filename`就可以配置输出路径，我这里是对于`build`命令会放在Application/Home/View目录再加上前面得到的pathname目录，而`dev`命令就只是pathname目录下，这时再加上前面`publicPath`的配置，对于项目中的例子运行`npm run dev`命令后你可以访问 localhost:8080/View/index/index.html 访问其中一个输出的HTML文件。

**Comment by cocody** [comment]
可以了，谢谢！
