### ISSUE TITLE
为什么我执行build命令后html文件被打包到Public目录下了呢

### ISSUE THREAD

**Issue by tianyuwu** [cnu4/Webpack-Vue-MultiplePage#4]

**Comment by cnu4** [comment]
确认 HtmlWebpackPlugin 插件的配置项 

[`filename: prod? '../Application/Home/View/' + pathname + '.html' : pathname + '.html'`](https://github.com/cnu4/Webpack-Vue-MultiplePage/blob/master/webpack.config.js#L101)

配置正确了

**Comment by tianyuwu** [comment]
配置是对的，只是我在mac环境下， 执行build命令时，process.env.NODE_ENV变量是undefinded，很奇怪的bug

**Comment by cnu4** [comment]
抱歉，demo 中 build 命令 `set NODE_ENV=production` 是在 Windows 中的写法。

试试把 package.json 中的 build 命令改成 `NODE_ENV=production webpack`

**Comment by tianyuwu** [comment]
对了，我想再问下，打包之前dev环境下，怎么访问对应的页面呢

**Comment by cnu4** [comment]
看 webpack 配置 output 的 publicPath 项和 HtmlWebpackPlugin 插件的 filename 配置项

demo 中 dev 环境下中分别是 `/View` 和` pathname + '.html'`

所以 demo 中通过 `http://localhost:8080/View/another/index.html` 可以访问到 another 模块下的 index 页面

**Comment by tianyuwu** [comment]
soga，谢谢你🙏，瞬间懂了
