### ISSUE TITLE
关于配置webpack的问题

### ISSUE THREAD

**Issue by sshien** [cnu4/Webpack-Vue-MultiplePage#6]
你好，很开心你的这个demo给我了很大的帮助。
在你的webpack其中有个配置我有点没看懂，
`babel: {
    presets: ['es2015'],
    plugins: ['transform-runtime']
  },
vue: { // vue 的配置
    loaders: {
      js: 'babel',
      css: ExtractTextPlugin.extract('vue-style-loader', 'css-loader')
    }
  },`
类似于这样的配置， 我不知道你怎么会这样写。我在babel的官网也没看到这样的配置，请问这样配置你是在哪里看到的呢。希望你能告诉下

**Comment by cnu4** [comment]
关于 `babel` 那个配置我也忘了在哪看到的参考配置，现在查询文档都是推荐新建 `.babelrc` 文件，在里面写配置。

vue 的配置可以参考 [ `vue-loader` 文档](https://vue-loader.vuejs.org/zh-cn/configurations/extract-css.html)
