### ISSUE TITLE
打包后info.html的css乱入了

### ISSUE THREAD

**Issue by bgl1987** [cnu4/Webpack-Vue-MultiplePage#7]
打包之后的info.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>info - Vue Webpack Example</title>
    
  <link href="/Public/css/vendors.css" rel="stylesheet"><link href="/Public/css/another/index.css" rel="stylesheet"><link href="/Public/css/index/index.css" rel="stylesheet"></head>
  <body>
    <p>info page</p>
    
  <script type="text/javascript" src="/Public/js/vendors.ede61ff4ad33ad1d9cf0.js"></script><script type="text/javascript" src="/Public/js/another/index.ede61ff4ad33ad1d9cf0.js"></script><script type="text/javascript" src="/Public/js/index/index.ede61ff4ad33ad1d9cf0.js"></script></body>
</html>

可以看到，它引入了所有的css

**Comment by dmwin72015** [comment]
这个感觉版本有点落后了，最新版永不了，所有js，css 被同时引用

**Comment by cnu4** [comment]
@bgl1987 是因为缺少了入口文件

**Comment by cnu4** [comment]
@dmwin72015 是指 webpack 版本有点落后了吗？其实这个例子只是提供一个在多页面下的思路，webpack 等工具升级后可能需要相应修改一下配置
