### ISSUE TITLE
怎么添加vue-router呢？

### ISSUE THREAD

**Issue by zhilianbi520** [cnu4/Webpack-Vue-MultiplePage#9]
求添加路由后的脚手架～🙏

**Comment by cnu4** [comment]
添加 vue-router 不需要改动 webpack 的配置

多页面架构下一般不需要用到 vue-router，但可能个别页面会有点复杂，这时可以在这个页面下引入 vue-router

首先按照 vue-router 官方指引安装后，在需要用的 vue-router 的页面的入口文件 index.js 初始化 vue router 即可

```js
const router = new VueRouter({
  { path: '/foo', component: Foo },
})
const app = new Vue({
  router
}).$mount('#app')
```

路由所需的组件可以放在注册路由的这个页面文件夹下面

**Comment by zhilianbi520** [comment]
@cnu4  收到，已解决添加路由问题
